Map<String, Map<String, String>> appStrings = {
  "en": {
    "profile": "Profile",
    "account_info": "Account Information",
    "name": "Name",
    "email": "Email Address",
    "configuration": "Configuration",
    "age": "Age Range",
    "language": "Language",
    "more_options": "More Options",
    "about": "About Auris",
    "privacy": "Privacy Policy",
    "help": "Help & Support",
    "sign_out": "Sign Out",
    "save": "Save & Continue",
    "board": "Board",
    "comm_board": "Communication Board",
    "suggestions": "Suggestions",
    "speak": "Speak",
    "clear": "Clear",
    "welcome": "Welcome back! 👋",
    "login_msg": "Sign in to continue using Auris",
    "register": "Register",
    "login": "Login",
    "design_title": "Design Vocabulary",
    "customizing_for": "Customizing for",
    "add_word_hint": "Add a new word...",
    "reset_defaults": "Reset to Recommended Defaults",
    "confirm_design": "Confirm Design",
  },
  "fr": {
    "profile": "Profil",
    "account_info": "Informations sur le compte",
    "name": "Nom",
    "email": "Adresse e-mail",
    "configuration": "Configuration",
    "age": "Tranche d'âge",
    "language": "Langue",
    "more_options": "Plus d'options",
    "about": "À propos d'Auris",
    "privacy": "Politique de confidentialité",
    "help": "Aide et support",
    "sign_out": "Se déconnecter",
    "save": "Enregistrer et continuer",
    "board": "Tableau",
    "comm_board": "Tableau de communication",
    "suggestions": "Suggestions",
    "speak": "Parler",
    "clear": "Effacer",
    "welcome": "Bon retour! 👋",
    "login_msg": "Connectez-vous pour continuer à utiliser Auris",
    "register": "S'inscrire",
    "login": "S'identifier",
    "design_title": "Concevoir le vocabulaire",
    "customizing_for": "Personnalisation pour",
    "add_word_hint": "Ajouter un nouveau mot...",
    "reset_defaults": "Réinitialiser aux valeurs recommandées",
    "confirm_design": "Confirmer la conception",
  },
  "es": {
    "profile": "Perfil",
    "account_info": "Información de la cuenta",
    "name": "Nombre",
    "email": "Correo electrónico",
    "configuration": "Configuración",
    "age": "Grupo de edad",
    "language": "Idioma",
    "more_options": "Más opciones",
    "about": "Sobre Auris",
    "privacy": "Política de privacidad",
    "help": "Ayuda y soporte",
    "sign_out": "Cerrar sesión",
    "save": "Guardar y continuar",
    "board": "Tablero",
    "comm_board": "Tablero de comunicación",
    "suggestions": "Sugerencias",
    "speak": "Hablar",
    "clear": "Limpiar",
    "welcome": "¡Bienvenido de nuevo! 👋",
    "login_msg": "Inicia sesión para usar Auris",
    "register": "Registrarse",
    "login": "Iniciar sesión",
    "design_title": "Diseñar vocabulario",
    "customizing_for": "Personalizando para",
    "add_word_hint": "Añadir una nueva palabra...",
    "reset_defaults": "Restablecer a valores recomendados",
    "confirm_design": "Confirmar diseño",
  },
  "de": {
    "profile": "Profil",
    "account_info": "Kontoinformationen",
    "name": "Name",
    "email": "E-Mail-Adresse",
    "configuration": "Konfiguration",
    "age": "Altersgruppe",
    "language": "Sprache",
    "more_options": "Weitere Optionen",
    "about": "Über Auris",
    "privacy": "Datenschutz-Bestimmungen",
    "help": "Hilfe & Support",
    "sign_out": "Abmelden",
    "save": "Speichern & Fortfahren",
    "board": "Brett",
    "comm_board": "Kommunikationsbrett",
    "suggestions": "Vorschläge",
    "speak": "Sprechen",
    "clear": "Löschen",
    "welcome": "Willkommen zurück! 👋",
    "login_msg": "Melden Sie sich an, um Auris zu nutzen",
    "register": "Registrieren",
    "login": "Anmelden",
    "design_title": "Wortschatz entwerfen",
    "customizing_for": "Anpassen für",
    "add_word_hint": "Neues Wort hinzufügen...",
    "reset_defaults": "Auf Standardwerte zurücksetzen",
    "confirm_design": "Design bestätigen",
  },
  "it": {
    "profile": "Profilo",
    "account_info": "Informazioni sull'Account",
    "name": "Nome",
    "email": "Indirizzo e-mail",
    "configuration": "Configurazione",
    "age": "Fascia d'età",
    "language": "Lingua",
    "more_options": "Altre opzioni",
    "about": "Informazioni su Auris",
    "privacy": "Informativa sulla privacy",
    "help": "Aiuto e supporto",
    "sign_out": "Disconnettersi",
    "save": "Salva e Continua",
    "board": "Tabellone",
    "comm_board": "Tabellone di Comunicazione",
    "suggestions": "Suggerimenti",
    "speak": "Parla",
    "clear": "Pulisci",
    "welcome": "Bentornato! 👋",
    "login_msg": "Accedi per continuare a usare Auris",
    "register": "Registrati",
    "login": "Accedi",
    "design_title": "Progetta Vocabolario",
    "customizing_for": "Personalizzazione per",
    "add_word_hint": "Aggiungi una nuova parola...",
    "reset_defaults": "Ripristina impostazioni consigliate",
    "confirm_design": "Conferma design",
  },
};
